package com.model;

/**
 * TGongzi generated by MyEclipse Persistence Tools
 */

public class TGongzi implements java.io.Serializable
{

	// Fields

	private Integer id;

	private Integer yuangongId;

	private String yuefen;
	
	private Integer jibengongzi;

	private Integer jiabanfei;

	private Integer gonglingfei;

	private Integer kaoqinfei;

	private Integer baoxianfei;

	private Integer jiangjin;

	private Integer wugongfei;

	private Integer gerenshui;

	private Integer shifagongzi;

	private String del;
	
	private String yuangongName;

	// Constructors

	/** default constructor */
	public TGongzi()
	{
	}

	/** full constructor */
	public TGongzi(Integer yuangongId, String yuefen, Integer jibengongzi,
			Integer jiabanfei, Integer gonglingfei, Integer kaoqinfei,
			Integer baoxianfei, Integer jiangjin, Integer wugongfei,
			Integer gerenshui, Integer shifagongzi, String del)
	{
		this.yuangongId = yuangongId;
		this.yuefen = yuefen;
		this.jibengongzi = jibengongzi;
		this.jiabanfei = jiabanfei;
		this.gonglingfei = gonglingfei;
		this.kaoqinfei = kaoqinfei;
		this.baoxianfei = baoxianfei;
		this.jiangjin = jiangjin;
		this.wugongfei = wugongfei;
		this.gerenshui = gerenshui;
		this.shifagongzi = shifagongzi;
		this.del = del;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Integer getYuangongId()
	{
		return this.yuangongId;
	}

	public void setYuangongId(Integer yuangongId)
	{
		this.yuangongId = yuangongId;
	}

	public String getYuefen()
	{
		return this.yuefen;
	}

	public void setYuefen(String yuefen)
	{
		this.yuefen = yuefen;
	}

	public Integer getJibengongzi()
	{
		return this.jibengongzi;
	}

	public void setJibengongzi(Integer jibengongzi)
	{
		this.jibengongzi = jibengongzi;
	}

	public Integer getJiabanfei()
	{
		return this.jiabanfei;
	}

	public void setJiabanfei(Integer jiabanfei)
	{
		this.jiabanfei = jiabanfei;
	}

	public Integer getGonglingfei()
	{
		return this.gonglingfei;
	}

	public void setGonglingfei(Integer gonglingfei)
	{
		this.gonglingfei = gonglingfei;
	}

	public Integer getKaoqinfei()
	{
		return this.kaoqinfei;
	}

	public String getYuangongName()
	{
		return yuangongName;
	}

	public void setYuangongName(String yuangongName)
	{
		this.yuangongName = yuangongName;
	}

	public void setKaoqinfei(Integer kaoqinfei)
	{
		this.kaoqinfei = kaoqinfei;
	}

	public Integer getBaoxianfei()
	{
		return this.baoxianfei;
	}

	public void setBaoxianfei(Integer baoxianfei)
	{
		this.baoxianfei = baoxianfei;
	}

	public Integer getJiangjin()
	{
		return this.jiangjin;
	}

	public void setJiangjin(Integer jiangjin)
	{
		this.jiangjin = jiangjin;
	}

	public Integer getWugongfei()
	{
		return this.wugongfei;
	}

	public void setWugongfei(Integer wugongfei)
	{
		this.wugongfei = wugongfei;
	}

	public Integer getGerenshui()
	{
		return this.gerenshui;
	}

	public void setGerenshui(Integer gerenshui)
	{
		this.gerenshui = gerenshui;
	}

	public Integer getShifagongzi()
	{
		return this.shifagongzi;
	}

	public void setShifagongzi(Integer shifagongzi)
	{
		this.shifagongzi = shifagongzi;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}