package com.model;

import java.util.Date;

/**
 * TJiangcheng generated by MyEclipse Persistence Tools
 */

public class TJiangcheng implements java.io.Serializable {

	// Fields

	private Integer jiangchengId;

	private String jiangchengDate;

	private String jiangchengXiangmu;
	
	private String jiangchengShuxing;

	private Integer jiangchengJine;

	private String jiangchengBeizhu;

	private Integer jiangchengYuangongId;

	private String jiangchengYuangongName;

	private String jiangchengOne1;

	private String jiangchengOne2;

	private String jiangchengOne3;

	private String jiangchengOne4;

	private String jiangchengOne5;

	private Integer jiangchengOne6;

	private Integer jiangchengOne7;

	private Date jiangchengOne8;

	private Date jiangchengOne9;

	private Long jiangchengOne10;

	// Constructors

	/** default constructor */
	public TJiangcheng() {
	}

	/** full constructor */
	public TJiangcheng(Date jiangchengDate, String jiangchengXiangmu,
			Integer jiangchengJine, String jiangchengBeizhu,
			Integer jiangchengUserId, String jiangchengUserName,
			String jiangchengUserOrg, String jiangchengUserSex,
			String jiangchengOne1, String jiangchengOne2,
			String jiangchengOne3, String jiangchengOne4,
			String jiangchengOne5, Integer jiangchengOne6,
			Integer jiangchengOne7, Date jiangchengOne8, Date jiangchengOne9,
			Long jiangchengOne10) {
		
		this.jiangchengXiangmu = jiangchengXiangmu;
		this.jiangchengJine = jiangchengJine;
		this.jiangchengBeizhu = jiangchengBeizhu;
		
		this.jiangchengOne1 = jiangchengOne1;
		this.jiangchengOne2 = jiangchengOne2;
		this.jiangchengOne3 = jiangchengOne3;
		this.jiangchengOne4 = jiangchengOne4;
		this.jiangchengOne5 = jiangchengOne5;
		this.jiangchengOne6 = jiangchengOne6;
		this.jiangchengOne7 = jiangchengOne7;
		this.jiangchengOne8 = jiangchengOne8;
		this.jiangchengOne9 = jiangchengOne9;
		this.jiangchengOne10 = jiangchengOne10;
	}

	// Property accessors

	public Integer getJiangchengId() {
		return this.jiangchengId;
	}

	public void setJiangchengId(Integer jiangchengId) {
		this.jiangchengId = jiangchengId;
	}


	public String getJiangchengShuxing() {
		return jiangchengShuxing;
	}

	public void setJiangchengShuxing(String jiangchengShuxing) {
		this.jiangchengShuxing = jiangchengShuxing;
	}

	public String getJiangchengDate() {
		return jiangchengDate;
	}

	public void setJiangchengDate(String jiangchengDate) {
		this.jiangchengDate = jiangchengDate;
	}

	public String getJiangchengXiangmu() {
		return this.jiangchengXiangmu;
	}

	public void setJiangchengXiangmu(String jiangchengXiangmu) {
		this.jiangchengXiangmu = jiangchengXiangmu;
	}

	public Integer getJiangchengJine() {
		return this.jiangchengJine;
	}

	public void setJiangchengJine(Integer jiangchengJine) {
		this.jiangchengJine = jiangchengJine;
	}

	public String getJiangchengBeizhu() {
		return this.jiangchengBeizhu;
	}

	public void setJiangchengBeizhu(String jiangchengBeizhu) {
		this.jiangchengBeizhu = jiangchengBeizhu;
	}


	public String getJiangchengOne1() {
		return this.jiangchengOne1;
	}

	public void setJiangchengOne1(String jiangchengOne1) {
		this.jiangchengOne1 = jiangchengOne1;
	}

	public String getJiangchengOne2() {
		return this.jiangchengOne2;
	}

	public void setJiangchengOne2(String jiangchengOne2) {
		this.jiangchengOne2 = jiangchengOne2;
	}

	public String getJiangchengOne3() {
		return this.jiangchengOne3;
	}

	public void setJiangchengOne3(String jiangchengOne3) {
		this.jiangchengOne3 = jiangchengOne3;
	}

	public String getJiangchengOne4() {
		return this.jiangchengOne4;
	}

	public void setJiangchengOne4(String jiangchengOne4) {
		this.jiangchengOne4 = jiangchengOne4;
	}

	public Integer getJiangchengYuangongId()
	{
		return jiangchengYuangongId;
	}

	public void setJiangchengYuangongId(Integer jiangchengYuangongId)
	{
		this.jiangchengYuangongId = jiangchengYuangongId;
	}

	public String getJiangchengYuangongName()
	{
		return jiangchengYuangongName;
	}

	public void setJiangchengYuangongName(String jiangchengYuangongName)
	{
		this.jiangchengYuangongName = jiangchengYuangongName;
	}

	public String getJiangchengOne5() {
		return this.jiangchengOne5;
	}

	public void setJiangchengOne5(String jiangchengOne5) {
		this.jiangchengOne5 = jiangchengOne5;
	}

	public Integer getJiangchengOne6() {
		return this.jiangchengOne6;
	}

	public void setJiangchengOne6(Integer jiangchengOne6) {
		this.jiangchengOne6 = jiangchengOne6;
	}

	public Integer getJiangchengOne7() {
		return this.jiangchengOne7;
	}

	public void setJiangchengOne7(Integer jiangchengOne7) {
		this.jiangchengOne7 = jiangchengOne7;
	}

	public Date getJiangchengOne8() {
		return this.jiangchengOne8;
	}

	public void setJiangchengOne8(Date jiangchengOne8) {
		this.jiangchengOne8 = jiangchengOne8;
	}

	public Date getJiangchengOne9() {
		return this.jiangchengOne9;
	}

	public void setJiangchengOne9(Date jiangchengOne9) {
		this.jiangchengOne9 = jiangchengOne9;
	}

	public Long getJiangchengOne10() {
		return this.jiangchengOne10;
	}

	public void setJiangchengOne10(Long jiangchengOne10) {
		this.jiangchengOne10 = jiangchengOne10;
	}

}