package com.model;

/**
 * TYuangong generated by MyEclipse Persistence Tools
 */

public class TYuangong implements java.io.Serializable
{

	// Fields

	private Integer yuangongId;

	private String yuangongName;

	private String yuangongSex;

	private Integer yuangongAge;

	private String yuangongXueli;

	private String yuangongZhiwei;

	private String yuangongAddress;

	private String yuangongTel;

	private String yuangongEmail;

	private String yuangongQq;

	private String yuangongLoginName;

	private String yuangongLoginPw;

	private Integer yuangongOrgId;
	
	private String type;

	private String del;
	
	private String yuangongOrgName;

	// Constructors

	/** default constructor */
	public TYuangong()
	{
	}

	/** full constructor */
	public TYuangong(String yuangongName, String yuangongSex,
			Integer yuangongAge, String yuangongXueli, String yuangongZhiwei,
			String yuangongAddress, String yuangongTel, String yuangongEmail,
			String yuangongQq, String yuangongLoginName,
			String yuangongLoginPw, Integer yuangongOrgId, String del)
	{
		this.yuangongName = yuangongName;
		this.yuangongSex = yuangongSex;
		this.yuangongAge = yuangongAge;
		this.yuangongXueli = yuangongXueli;
		this.yuangongZhiwei = yuangongZhiwei;
		this.yuangongAddress = yuangongAddress;
		this.yuangongTel = yuangongTel;
		this.yuangongEmail = yuangongEmail;
		this.yuangongQq = yuangongQq;
		this.yuangongLoginName = yuangongLoginName;
		this.yuangongLoginPw = yuangongLoginPw;
		this.yuangongOrgId = yuangongOrgId;
		this.del = del;
	}

	// Property accessors

	public Integer getYuangongId()
	{
		return this.yuangongId;
	}

	public void setYuangongId(Integer yuangongId)
	{
		this.yuangongId = yuangongId;
	}

	public String getYuangongName()
	{
		return this.yuangongName;
	}

	public void setYuangongName(String yuangongName)
	{
		this.yuangongName = yuangongName;
	}

	public String getYuangongSex()
	{
		return this.yuangongSex;
	}

	public void setYuangongSex(String yuangongSex)
	{
		this.yuangongSex = yuangongSex;
	}

	public Integer getYuangongAge()
	{
		return this.yuangongAge;
	}

	public void setYuangongAge(Integer yuangongAge)
	{
		this.yuangongAge = yuangongAge;
	}

	public String getYuangongXueli()
	{
		return this.yuangongXueli;
	}

	public void setYuangongXueli(String yuangongXueli)
	{
		this.yuangongXueli = yuangongXueli;
	}

	public String getYuangongZhiwei()
	{
		return this.yuangongZhiwei;
	}

	public void setYuangongZhiwei(String yuangongZhiwei)
	{
		this.yuangongZhiwei = yuangongZhiwei;
	}

	public String getYuangongAddress()
	{
		return this.yuangongAddress;
	}

	public void setYuangongAddress(String yuangongAddress)
	{
		this.yuangongAddress = yuangongAddress;
	}

	public String getYuangongTel()
	{
		return this.yuangongTel;
	}

	public void setYuangongTel(String yuangongTel)
	{
		this.yuangongTel = yuangongTel;
	}

	public String getType()
	{
		return type;
	}

	public void setType(String type)
	{
		this.type = type;
	}


	public String getYuangongEmail() {
		return yuangongEmail;
	}

	public void setYuangongEmail(String yuangongEmail) {
		this.yuangongEmail = yuangongEmail;
	}

	public String getYuangongQq()
	{
		return this.yuangongQq;
	}

	public void setYuangongQq(String yuangongQq)
	{
		this.yuangongQq = yuangongQq;
	}

	public String getYuangongLoginName()
	{
		return this.yuangongLoginName;
	}

	public void setYuangongLoginName(String yuangongLoginName)
	{
		this.yuangongLoginName = yuangongLoginName;
	}

	public String getYuangongLoginPw()
	{
		return this.yuangongLoginPw;
	}

	public void setYuangongLoginPw(String yuangongLoginPw)
	{
		this.yuangongLoginPw = yuangongLoginPw;
	}

	public Integer getYuangongOrgId()
	{
		return this.yuangongOrgId;
	}

	public void setYuangongOrgId(Integer yuangongOrgId)
	{
		this.yuangongOrgId = yuangongOrgId;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

	public String getYuangongOrgName()
	{
		return yuangongOrgName;
	}

	public void setYuangongOrgName(String yuangongOrgName)
	{
		this.yuangongOrgName = yuangongOrgName;
	}

}